### ISSUE TITLE
Nansat OpenDAP does not support handling of 4 dimensional files

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#369]
## Description
`Opendap` class supposed to be a parent for all OpenDAP mappers supports only **3-dimensional** arrays, i.e  `[time][y][x]`. However, Many datasets, such as model outputs (see [AROME-Arctic](https://thredds.met.no/thredds/dodsC/aromearcticarchive/2017/11/29/arome_arctic_full_2_5km_20171129T03Z.nc.html) example), are provided as **4-dimensional datasets**, i.e. `[time][height/depth][y][x]`. Therefore the class should be updated/extended for the handling of 4d (and more?) datasets.

## Solution
Find a generic solution for mapping datasets with any number of dimensions and update Opendap class with that. Information about dimensions for each single variable is usually provided in NetCDF files (see [NetCDF: Dimensions](https://www.unidata.ucar.edu/software/netcdf/docs/group__dimensions.html)). Thus, information can be extracted while processing of a `Dataset` and used for generation of a URL for `SourceFile` metadata.

## TODO

- [x] Find a solution for mapping datasets which contain variables described in 2, 3 or 4-d space
- [x] Refactor `Opendap` class
- [x] Update documentation and comments in `Opendap` class
- [x] Update Opendap class with a new solution
- [x] Tests
