### ISSUE TITLE
Domain.shape method should be a property

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#411]
## Idea
The `Domain` class has a `shape` method which returns the (y, x) tuple. The method is inherited by the `Nansat` object and widely used. The idea is to make a `shape` property instead of the method. It will be more consistent with the `numpy` then.

## TODO

- [ ] Create a `shape` property in the `Domain` class by analogy with the existing `shape` method 

- [ ] Create a deprication warning in the `shape` method 

- [ ] Fix the mappers and all other code using the `shape` method 

- [ ] Fix the tests
