### ISSUE TITLE
Distance to the nearest coast

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#442]
### **Problem**
The distance to the nearest coastline is a kind of information which highly used in the satellite data processing (masking observations). Adding this functionality (i.e. ability to get a distance to the nearest coast for each pixel in a given domain) would be very useful. 
### **Solution**
NASA OBPG provides the open-source product (https://oceancolor.gsfc.nasa.gov/docs/distfromcoast/) which could be integrated along with the MOD44W product.
### **TODO** 
- [x] Develop a method (see watermask) in the nansat.tools
- [x] Add a recipe to documentation about getting auxiliary data 
- [x] Tests

**Comment by korvinos** [comment]
The proposed approach produces a so-called "circular dependency import" issue due to circular calling of the `nansat.tools` and `nansat.domain` or `nansat.nansat` modules. Therefore the `nansat.tools` must be separated between the `nansat.tools` and the `nansat.utils` to avoid this problem (also in the future).

- [ ] Define functions that are imported by other nansat modules and move them to the `nansat.utils`.
- [ ] Refactor all package according to the new structural changes

**Comment by akorosov** [comment]
Hi @korvinos , what's the status here? I'd like to move plot_domain_map to nansat.tools

**Comment by akorosov** [comment]
Do you mind if I make a branch from https://github.com/nansencenter/nansat/commit/7010020771460fbe0a8002691845a87426bb49df

And then we can merge it into develop (with a PR, etc)?

Then I make another branch for my development and then I can add tools and add some functions that use Nansat.

**Comment by korvinos** [comment]
@akorosov  actually it should works (when I run all tests locally) However the Travis fails. Maybe you could have a look on the log of travis, please? Once it is resolved I could merge it

**Comment by korvinos** [comment]
closed in #461
